# Generated by Django 4.1.1 on 2022-09-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(max_length=14, unique=True)),
                ("titleType", models.CharField(max_length=100)),
                ("primary_title", models.CharField(max_length=150)),
                ("runtime", models.IntegerField(default=0)),
                ("genres", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(max_length=14, unique=True)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=2),
                ),
                ("votes", models.IntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.movie",
                    ),
                ),
            ],
        ),
    ]
